"""empty message

Revision ID: e29625c6e2b0
Revises: 
Create Date: 2020-03-22 21:54:02.509356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29625c6e2b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
